### ISSUE TITLE
Error afer run offdroid list-packages

### ISSUE THREAD

**Issue by agasigp** [icefapper/offdroid#2]
Hi, I have a problem/issue. I got an error after run offdroid list-package command. The error is in the picture. I'm running Ubuntu 16.04. Any suggestion to fix my issue? Thanks.
![screenshot from 2017-01-23 11-12-10](https://cloud.githubusercontent.com/assets/2476867/22191439/5038b8ce-e15d-11e6-9ae1-f745a37fa97c.png)

**Comment by icefapper** [comment]
Hi and thank you for using offdroid!

This issue is most probably because there is something wrong with the files in your `offdroid-xml` folder.

For example, because access to Google's android repository is forbidden from my country,  I actually encounter this problem whenever I try to download the "component lists" (i.e, the repository xmls) without using an actual proxy:
```sh
offdroid fetch-xmls # will fail
```

but whenever I use a proxy, the problem goes away:
```sh
offdroid fetch-xmls through http://192.34.58.204:3128 # could be any valid proxy, e.g, socks5://127.0.0.1:9150 if you are running tor
```

I would be very grateful if you could share the contents of, in your case, `/media/agasigp/DATA/Software/Android/android-sdk-repo/.offdroid-xml`, so that I have a chance to further look into the issue. Thanks again!

**Comment by agasigp** [comment]
I found the problem. I run this command : **offdroid fetch-xmls through socks5://127.0.0.1:9150** as instructed in the example. In the example, you're using proxy because Google's android repository is forbidden in your country. In Indonesia, my country, google is not forbidden, therefore I'm not required to use proxy, so I just need to run **offdroid fetch-xmls** and it works well. Thanks for your explanation.

**Comment by icefapper** [comment]
@agasigp thanks for actually pointing that out -- turns out it has been a shortcoming on my side, giving he examples from my own stance rather than that of the user. 

I'm going to adjust the usage example to reflect that. Best wishes!
